# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='watch.NeighborHood')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='join',
            name='hood_id',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
