# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20181023_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborHood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='watch.NeighborHood'),
        ),
    ]
