# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20181022_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='view',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
